# K means Clustering 

https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

## Dummy Data Generation

In [2]:
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])

## Clustering

In [3]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0)
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [5]:
kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [6]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])

## Prediction

In [7]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0], dtype=int32)